timelock: tests the operation store dump
smartcontractkit/timelock-worker pull request #33
Opened 2024-02-06 14:27 UTC by MStreet3

Tests that dumping the operation store actually writes the expected values to file.  Injects a time faker function and refactors dumpOperationStore to improve testability.

2024-02-06 17:16 UTC, fbac requested changes

2024-02-06 17:16 UTC, fbac commented on pkg/timelock/scheduler.go
> +// TODO(mstreet3): dumpOperationStore accepts a now func to mock out the time during tests.  Consider
Can we remove this TODO comment and create a GH issue out of it?

2024-02-06 17:16 UTC, fbac commented on pkg/timelock/scheduler.go
> +func writeOperationStore(
nit: Now that you extracted the writeOperationStore I think it makes sense for the timelock-worker store to be independent from the timelock-worker itself, so the tw interacts with it via an interface. This is quite a heavy work, so no need to address it here, I'll create an issue.

2024-02-06 22:37 UTC, MStreet3 commented on pkg/timelock/scheduler.go
> +func writeOperationStore(
Agreed.. I wanted to stop short of that while increasing some test coverage. I think the TODO above would be handled in such an effort to extract the store.

2024-02-06 23:08 UTC, MStreet3 commented on pkg/timelock/scheduler.go
> +func writeOperationStore(
https://github.com/smartcontractkit/timelock-worker/issues/34

2024-02-07 06:19 UTC, fbac approved these changes

2024-02-07 12:16 UTC, merged